### ISSUE TITLE
Are there any indexes not in English language?

### ISSUE THREAD

**Issue by trashbirdecology** [UW-xDD/user_forum#2]
Tried to ping the database using some spanish/portuguese search terms and came back with zero results. 

Just curious whether searching for non-english terms is futile?

**Comment by iross** [comment]
Hi Jessica—
Most of our holdings are in English, so that’s what we’ve used for indexing. Depending on the route you’re interested in, you may have a little more success searching with a “no_word_stemming=true” parameter. It does a stricter match instead of trying to match by an English root word.


On March 18, 2020 at 10:28:35 AM, Jessica Burnett (notifications@github.com) wrote:

Tried to ping the database using some spanish/portuguese search terms and came back with zero results.

Just curious whether searching for non-english terms is futile?

**Comment by trashbirdecology** [comment]
Thanks for the response, which I only just saw :(
 
This wasn't a feature request, so I will close issue.
